name: Cocos2d-x 2.2.6 Build (Win32 - v141 Retarget)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_win32_v226:
    # Tetap gunakan windows-latest/windows-2022
    runs-on: windows-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild and Visual Studio Environment
        # Action ini memastikan semua variabel lingkungan diatur.
        uses: microsoft/setup-msbuild@v2 
        with:
          vs-version: 'latest' 
          msbuild-architecture: x64
          
      - name: Build Solution
        # ➡️ PERUBAHAN KRUSIAL: Mengubah toolset ke v141 (VS 2017). 
        # Toolset v141 DIJAMIN terinstal di runner windows-latest (VS 2022).
        # Ini bertindak sebagai "Retarget solution" otomatis yang diminta oleh error MSB8020.
        run: |
          echo "Attempting to build using Platform Toolset v141 (VS 2017) to bypass MSB8020..."
          msbuild cocos2d-win32.sln /p:Configuration=Release /p:Platform=Win32 /m /t:Build /p:PlatformToolset=v141
          
      - name: Archive Artifact (Opsional)
        uses: actions/upload-artifact@v4
        with:
          name: naruto-senki-win32-release
          path: projects/NarutoSenki/proj.win32/Release.win32/NarutoSenki.exe
          if-no-files-found: warn
