name: CI Build Windows (Naruto Senki)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_win32:
    # Menggunakan runner terbaru, yang memiliki VS 2022 (v143 toolset)
    runs-on: windows-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Pastikan semua submodule Cocos2d-x ditarik
          submodules: recursive

      - name: Setup MSBuild and Visual Studio Environment
        # Mengatur path dan variabel lingkungan untuk MSBuild (VS 2022)
        uses: microsoft/setup-msbuild@v2 
        with:
          vs-version: 'latest' 
          msbuild-architecture: x64
          
      # OPSI 1: Build Menggunakan MSBuild (Paling Andal di CI)
      - name: Build Solution (Release|Win32)
        # Karena README menyarankan VS 2022, kita asumsikan toolset modern default (v143)
        # dapat digunakan tanpa memaksakan toolset lama (v120 atau v141).
        run: |
          echo "Building cocos2d-win32.sln using default VS 2022 Toolset..."
          msbuild cocos2d-win32.sln /p:Configuration=Release /p:Platform=Win32 /m /t:Build
          
          # Jika gagal dengan error MSB8020 lagi, coba paksa ke toolset VS 2019 (v142):
          # msbuild cocos2d-win32.sln /p:Configuration=Release /p:Platform=Win32 /m /t:Build /p:PlatformToolset=v142

      # OPSI 2: Build Menggunakan build.bat (Alternatif jika Anda memerlukannya)
      # - name: Run custom build.bat
      #   run: |
      #     .\build.bat
      
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: naruto-senki-win32-release
          # Berdasarkan struktur Anda: output harusnya ada di __BIN__
          # Namun, output MSBuild biasanya default ke proj.win32\Release.win32
          path: |
            projects/NarutoSenki/proj.win32/Release.win32/NarutoSenki.exe
            projects/NarutoSenki/__BIN__/NarutoSenki.exe
            
          if-no-files-found: warn
