name: Cocos2d-x 2.2.6 Build (Win32 - Release)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build_win32_v226:
    runs-on: windows-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # ➡️ LANGKAH KRUSIAL: Memastikan VS 2013 Toolset (v120) terinstal
      - name: Install Missing Visual Studio 2013 Toolset (v120)
        shell: powershell
        run: |
          # 1. Tentukan jalur untuk vswhere dan vs_installer
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $installerPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe"
          
          if (-not (Test-Path $vswhere) -or -not (Test-Path $installerPath)) {
              throw "Visual Studio Installer tools not found."
          }
          
          # 2. Temukan jalur instalasi VS 2022
          $vsPath = & "$vswhere" -latest -property installationPath
          if (-not $vsPath) {
              throw "VS 2022 installation path not found."
          }
          Write-Host "Found VS Installation Path: $vsPath"
          
          # 3. Tambahkan komponen Toolset v120 C++
          # Menggunakan ID komponen yang ditujukan untuk kompiler/toolset v120 untuk desktop.
          # Menambahkan --wait adalah kunci agar GitHub Actions menunggu proses instalasi selesai.
          Write-Host "Installing Microsoft.VisualStudio.Component.VC.v120.x86.v120_tools (VS 2013 Toolset)..."
          & "$installerPath" modify --installPath "$vsPath" --add Microsoft.VisualStudio.Component.VC.v120.x86.v120_tools --quiet --norestart --wait
          
          if ($LASTEXITCODE -ne 0) {
              throw "FAILED to install VS 2013 (v120) toolset. Exit Code: $LASTEXITCODE"
          }
          Write-Host "VS 2013 Toolset (v120) installation SUCCESSFUL."

      - name: Setup MSBuild and Visual Studio Environment
        # Panggil Setup MSBuild SETELAH toolset diinstal.
        uses: microsoft/setup-msbuild@v2 
        with:
          vs-version: 'latest' 
          msbuild-architecture: x64
          
      - name: Build Solution
        # Toolset v120 sekarang seharusnya sudah tersedia untuk MSBuild.
        run: |
          msbuild cocos2d-win32.sln /p:Configuration=Release /p:Platform=Win32 /m /t:Build /p:PlatformToolset=v120
          
      - name: Archive Artifact (Opsional)
        uses: actions/upload-artifact@v4
        with:
          name: naruto-senki-win32-release
          path: projects/NarutoSenki/proj.win32/Release.win32/NarutoSenki.exe
          if-no-files-found: warn
